version: "3.3"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3004:3000
    environment:
      - PG_PASSWORD=123456
      - PG_DB=vainawebdb
      - PG_USER=postgres
      - PG_HOST=vainaweb
      - SECRET=verysecret
    volumes:
      - .:/code

  vainaweb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vainawebdb
    ports:
      - 5435:5432
